[package]
name = "dietpi-dashboard"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["rt", "macros", "time", "sync", "fs", "process"] }
include_dir = {version = "0.7.2", optional = true}
futures = "0.3.24"
pty-process = "0.2.0"
psutil = "3.2.2"
infer = { version = "0.9.0", default-features = false }
ring = "0.16.20"
figment = { version = "0.10", features = ["toml", "env"] }
if-addrs = "0.7.0"
zip = { version = "0.6.2", default-features = false, features = ["time"] }
walkdir = "2.3.2"
jsonwebtoken = { version = "8.1.1", default-features = false }
serde = { version = "1.0.145", features = ["derive"] }
anyhow = "1.0.65"
once_cell = "1.15.0"
serde_json = "1.0.86"
tracing = { version = "0.1.36", features = ["release_max_level_debug"] }
tracing-subscriber = "0.3.15"
hyper = { version = "0.14.20", features = ["server", "http1", "tcp"] }
tokio-tungstenite = "0.17.2"
tokio-rustls = "0.23.4"
rustls-pemfile = "1.0.1"
getrandom = "0.2.7"
hex = "0.4.3"

[features]
default = ["frontend"]
frontend = ["include_dir"]

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
strip = true

[profile.release.package.serde]
opt-level = 3

[profile.release.package.psutil]
opt-level = 3

[profile.release.package.zip]
opt-level = 3

[profile.release.package."*"]
opt-level = "s"

[build-dependencies]
flate2 = "1.0.24"
rerun_in_except = "0.1.2"
walkdir = "2.3.2"

# Install node.js, enable corepack for yarn, and create required directories
[package.metadata.cross.build]
pre-build = ["curl -fsSL https://deb.nodesource.com/setup_16.x | bash", "apt-get install -y nodejs", "corepack enable", "mkdir /.node && chmod 777 /.node", "mkdir /.yarn && chmod 777 /.yarn"]
