[package]
name = "dietpi-dashboard"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = [
    "rt",
    "macros",
    "time",
    "sync",
    "fs",
    "process",
] }
include_dir = { version = "0.7.3", optional = true }
futures = "0.3.26"
pty-process = "0.2.0"
psutil = "3.2.2"
infer = { version = "0.13.0", default-features = false }
ring = "0.16.20"
figment = { version = "0.10", features = ["toml", "env"] }
if-addrs = "0.10.1"
zip = { version = "0.6.4", default-features = false, features = ["time"] }
walkdir = "2.3.2"
jsonwebtoken = { version = "8.2.0", default-features = false }
serde = { version = "1.0.154", features = ["derive"] }
anyhow = "1.0.69"
once_cell = "1.17.1"
serde_json = "1.0.94"
tracing = { version = "0.1.37", features = ["release_max_level_debug"] }
tracing-subscriber = "0.3.16"
hyper = { version = "0.14.25", features = ["server", "http1", "tcp"] }
tokio-tungstenite = "0.18.0"
tokio-rustls = "0.23.4"
rustls-pemfile = "1.0.2"
getrandom = "0.2.8"
hex = "0.4.3"

[features]
default = ["frontend"]
frontend = ["include_dir"]

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
strip = true

[profile.release.package.serde]
opt-level = 3

[profile.release.package.psutil]
opt-level = 3

[profile.release.package.zip]
opt-level = 3

[profile.release.package."*"]
opt-level = "s"

[build-dependencies]
flate2 = "1.0.25"
rerun_in_except = "0.1.2"
walkdir = "2.3.2"

# Install node.js, enable corepack for pnpm, and create required directories
[package.metadata.cross.build]
pre-build = [
    "curl -fsSL https://deb.nodesource.com/setup_16.x | bash",
    "apt-get install -y nodejs",
    "corepack enable",
    "mkdir /.cache && chmod 777 /.cache"
]
