# Log level
# - Options: "off", "error", "warn", "info", "debug", "trace"
# - Default: "info"
#log_level = "info"

# TCP network port
# - Default: 5252
#port = 5252

# TLS for HTTPS
# - Default: false
#tls = false
#cert = "/path/to/cert"
#key = "/path/to/key"

# Path to public key file of frontend node
# Needed to use multiple nodes
#pub_key="/path/to/pubkey"

# User to login to on the terminal
# Use "manual" to show a login prompt instead of auto-login
# - Default: "root"
#terminal_user = "root"

# Check for updates
# This will do 1 GitHub API call per day
# - Default: true
#update_check = true

# Preferred temperature unit
# - Options: fahrenheit, celsius
# - Default: "celsius"
#temp_unit = "celsius"
