[package]
name = "dietpi-dashboard"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = {version = "0.3.1", default-features = false, features = ["compression", "websocket", "tls"]}
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
simple_logger = "1.13.0"
log = "0.4.14"
include_dir = "0.6.2"
lazy_static = "1.4.0"
futures = "0.3.17"
nanoserde = "0.1.29"
pty-process = "0.1.0"
heim = { git = "https://github.com/heim-rs/heim", features = ["cpu", "disk", "host", "memory", "net", "process"] }
infer = { version = "0.5.0", default-features = false }

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
