[package]
name = "dietpi-dashboard"
version = "0.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = {version = "0.3.2", default-features = false, features = ["compression", "websocket", "tls"]}
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync"] }
num_cpus = "1.13.1"
simple_logger = "1.16.0"
log = "0.4.14"
include_dir = "0.7.2"
lazy_static = "1.4.0"
futures = "0.3.19"
nanoserde = "0.1.29"
pty-process = "0.2.0"
heim = { git = "https://github.com/heim-rs/heim", features = ["cpu", "disk", "host", "memory", "net", "process"] }
infer = { version = "0.5.0", default-features = false }
jwts = "0.2.3"
sha2 = "0.10.0"

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
incremental = false
