name: Daily Build
on: 
  schedule:
    - cron: "00 18 * * *"

jobs:
  debugBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: $GITHUB_WORKSPACE/src/frontend/yarn.lock    
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
       - name: Install Yarn Dependencies
         run: |
         cd $GITHUB_WORKSPACE/src/frontend
         yarn install
