name: Dependabot Lockfile Fix
on:
  - pull_request_target

jobs:
  fix-lockfile:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.head.ref, 'dependabot/npm_and_yarn/')

    env:
      YARN_ENABLE_SCRIPTS: false
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPENDABOT_PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 2

      - run: git checkout HEAD~1 yarn.lock

      - run: yarn install --mode=skip-build
        working-directory: frontend

      - run: yarn dedupe
        working-directory: frontend

      - name: Commit yarn.lock
        run: |
          git config user.name "dependabot-fix"
          git config user.email "dependabot-fix@github.com"
          git add frontend/yarn.lock
          git commit -m '[dependabot skip] Fix yarn.lock'
          git push