name: Build
on: push

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'docs') && !startsWith(github.event.head_commit.message, 'style')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Lint (rustfmt)
        working-directory: src/backend
        run: cargo fmt -- --check
      - name: Install other Rust targets
        run: |
          rustup target add x86_64-unknown-linux-musl
          rustup target add arm-unknown-linux-musleabihf
          rustup target add armv7-unknown-linux-musleabihf
          rustup target add aarch64-unknown-linux-musl
      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: src/backend
      - name: Lint (clippy)
        working-directory: src/backend
        run: |
          mkdir dist
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Install Cross-compiler
        run: cargo install cross
      - name: Install Yarn Dependencies
        working-directory: src/frontend
        run: yarn install
      - name: Build frontend
        working-directory: src/frontend
        run: yarn build
      - name: Copy "dist" folder
        run: cp -r src/frontend/dist/. src/backend/dist/
      - name: Build x86_64
        working-directory: src/backend
        run: cross build --release --target x86_64-unknown-linux-musl
      - name: Build armv6l
        working-directory: src/backend
        run: cross build --release --target arm-unknown-linux-musleabihf
      - name: Build armv7l
        working-directory: src/backend
        run: cross build --release --target armv7-unknown-linux-musleabihf
      - name: Build aarch64
        working-directory: src/backend
        run: cross build --release --target aarch64-unknown-linux-musl
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-x86_64
          path: src/backend/target/x86_64-unknown-linux-musl/release/dietpi-dashboard
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-armv6l
          path: src/backend/target/arm-unknown-linux-musleabihf/release/dietpi-dashboard
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-armv7l
          path: src/backend/target/armv7-unknown-linux-musleabihf/release/dietpi-dashboard
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-aarch64
          path: src/backend/target/aarch64-unknown-linux-musl/release/dietpi-dashboard
      - name: Build x86_64 (backend only)
        working-directory: src/backend
        run: cross build --release --target x86_64-unknown-linux-musl --no-default-features
      - name: Build armv6l (backend only)
        working-directory: src/backend
        run: cross build --release --target arm-unknown-linux-musleabihf --no-default-features
      - name: Build armv7l (backend only)
        working-directory: src/backend
        run: cross build --release --target armv7-unknown-linux-musleabihf --no-default-features
      - name: Build aarch64 (backend only)
        working-directory: src/backend
        run: cross build --release --target aarch64-unknown-linux-musl --no-default-features
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-x86_64-backend
          path: src/backend/target/x86_64-unknown-linux-musl/release/dietpi-dashboard
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-armv6l-backend
          path: src/backend/target/arm-unknown-linux-musleabihf/release/dietpi-dashboard
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-armv7l-backend
          path: src/backend/target/armv7-unknown-linux-musleabihf/release/dietpi-dashboard
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-aarch64-backend
          path: src/backend/target/aarch64-unknown-linux-musl/release/dietpi-dashboard

