name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install other Rust targets
        run: |
          rustup target add arm-unknown-linux-gnueabihf
          rustup target add armv7-unknown-linux-gnueabihf
          rustup target add aarch64-unknown-linux-gnu
      - name: Install Rust cross-compiler
        run: cargo install cross
      - name: Install Yarn Dependencies
        working-directory: src/frontend
        run: yarn install
      - name: Build frontend
        working-directory: src/frontend
        run: yarn build
      - name: Copy "dist" folder
        run: cp -r $GITHUB_WORKSPACE/src/frontend/dist $GITHUB_WORKSPACE/src/backend
      - name: Build amd64
        working-directory: src/backend
        run: cargo build --release --manifest-path src/backend/Cargo.toml
      #- uses: actions-rs/cargo@v1
        #with:
          #use-cross: true
          #command: build
          #args: --release --target arm-unknown-linux-gnueabihf --manifest-path src/backend/Cargo.toml
      - name: Build armv7
        working-directory: src/backend
        run: cross build--release --target armv7-unknown-linux-gnueabihf
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-gnu --manifest-path src/backend/Cargo.toml
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: $GITHUB_WORKSPACE/src/backend
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-amd64
          path: $GITHUB_WORKSPACE/src/backend/target/release/dietpi_dashboard
      #- uses: actions/upload-artifact@v2
        #with:
          #name: dietpi-dashboard-armv6
          #path: $GITHUB_WORKSPACE/src/backend/target/arm-unknown-linux-gnueabihf/release/dietpi_dashboard
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-armv7
          path: $GITHUB_WORKSPACE/src/backend/target/armv7-unknown-linux-gnueabihf/release/dietpi_dashboard
      - uses: actions/upload-artifact@v2
        with:
          name: dietpi-dashboard-armv8
          path: $GITHUB_WORKSPACE/src/backend/target/aarch64-unknown-linux-gnu/release/dietpi_dashboard

